In [1]:
import numpy as np

In [8]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
c = a*b
print (c)

[[ 0.12657129 -0.03543531  0.40851877]
 [-0.00476952 -0.50866205  0.29952851]
 [ 0.02435189  0.84645704  0.21694011]
 [ 0.03769435  1.52631481 -0.75571911]]


In [10]:
c.shape

(4, 3)

In [11]:
d= np.array([[1,2,3],[2,3,4]])


In [15]:
a=np.array([[1,1],[1,-1]])
b=np.array([[2],[3]])
c=a+b
print(c)

[[3 3]
 [4 2]]
